### ISSUE TITLE
System.InvalidOperationException: /bin/stty: invalid argument ‘11520’

### ISSUE THREAD

**Issue by Zeelize** [crozone/LinuxSerialPort#12]
I am getting error:
```
System.InvalidOperationException: /bin/stty: invalid argument ‘11520’
Try '/bin/stty --help' for more information.

   at crozone.SerialPorts.LinuxSerialPort.Helpers.SttyExecution.CallStty(String sttyParams)
   at crozone.SerialPorts.LinuxSerialPort.Helpers.SttyExecution.SetTtyWithParam(IEnumerable`1 arguments)
   at crozone.SerialPorts.LinuxSerialPort.LinuxSerialPort.SetTtyOnSerial(IEnumerable`1 sttyArguments)
   at crozone.SerialPorts.LinuxSerialPort.LinuxSerialPort.SetAllSerialParams()
   at crozone.SerialPorts.LinuxSerialPort.LinuxSerialPort.Open()
```

when running application. What is the problem please? I found this library unsable with this problem...

**Comment by crozone** [comment]
I won't know for sure unless you can port some example code, but it appears that you may be using 11520 as the `BaudRate`.

11520 isn't a common speed, did you meant to use 115200 instead?

**Comment by Zeelize** [comment]
Oh I think that was a problem, I cant believe I made such an error. Closing issue :)

**Comment by crozone** [comment]
No worries, glad to help!
